### ISSUE TITLE
Release for 32C3

### ISSUE THREAD

**Issue by clonejo** [tuxmobil/CampFahrplan#105]
While the C3 is still over two weeks away, a timely release would be very cool. (before christmas?) I personally use the app to choose which talks to watch before the Congress.

I tested the 32C3 schedule with the current release (on F-Droid) using the "alternate URL" and the only issues I noticed are the 31C3 design (obviously) and a broken colour scheme for the Security and Failosophy tracks (white text on a light grey background, see also #104).

This depends on the release of the Congress design (last year it released on day 0), which would be quite late. A generically designed release (maybe keep the 31C3 design) seems sensible.

**Comment by johnjohndoe** [comment]
[The schedule for 32C3 has been released at 11.12.2015.](https://twitter.com/chaosupdates/status/675109388982571009).
I am already trying to find out if there is a design/color scheme/logo prepared.

**Comment by iggs0** [comment]
@johnjohndoe highly appreciated if you update the app :-). Let me know if I can pay you with mate or beer at 32c3

**Comment by johnjohndoe** [comment]
@iggs0 I have to clarify that I am just an ordinary contributor as anyone else - I do not have write or merge access. @tuxmobil is in charge of preparing the app for 32c3 and publishing a release. However, anyone can help to fix the bugs or implement features which are listed in the issue tracker.

**Comment by bjoernb** [comment]
The design is online: https://events.ccc.de/congress/2015/wiki/Static:Design

**Comment by johnjohndoe** [comment]
@bjoernb Thank you - @tuxmobil already added it in the 32c3 branch.

**Comment by ajdergute** [comment]
Thanks a lot. The new design is very cool.

**Comment by bjoernb** [comment]
will there also be a release update for the fdroid application?

**Comment by clonejo** [comment]
On 22.12.2015 22:15, bjoernb wrote:
>
> will there also be a release update for the fdroid application?
>
Also don't forget to update the listing name and logo this time, the
31C3 release is listed as “30C3 Schedule (Congress)”
(https://f-droid.org/repository/browse/?fdid=nerd.tuxmobil.fahrplan.congress).

**Comment by tuxmobil** [comment]
The app is in the Play Store (built from 65b5ca2dc5a381a30027223884481b795a708dc5). I haven't done the fdroid releases in the past. I hope the same people will do so that did that in the past years.

**Comment by sedrubal** [comment]
Is it possoble to make one App for all events with one name and to receive the current schedules and artwork the user has only to change the APIs URL and there are preconfigured URLs for the next events?

**Comment by tuxmobil** [comment]
That would require that the backend would deliver those meta-informations in a defined way. That's not the case as of today. The artwork has to be prepared to meet the specifications for an android app and that would require the backend to deliever this as well, as well as for other mobile platforms with other needs. Due to this needs and since we are not the backend guys, I do not see this happen in the medium term.

**Comment by sedrubal** [comment]
Ah OK and what's about providing a second api for artwork? ;)

**Comment by tuxmobil** [comment]
We'd love to see improvements on API for content rather than artwork first. Despite that, this is probably the wrong audience as we're doing the app only, not the backend/APIs.
