### ISSUE TITLE
default setting for alarm advance

### ISSUE THREAD

**Issue by ThomasWaldmann** [tuxmobil/CampFahrplan#121]
it currently defaults to "none" (0 minutes) which is a bit impractical as the site is quite large and often you have to pack your stuff together (and I guess we also want to avoid a lot of people entering the talks after they began).

so, being able to set a different default (like 10 or 15 minutes) would save quite some touches.

**Comment by ThomasWaldmann** [comment]
(as a quick hack, one could also just modify the builtin default to 10 or 15 instead of 0)

**Comment by johnjohndoe** [comment]
:+1:

**Comment by johnjohndoe** [comment]
I work on this right now.

**Comment by tuxmobil** [comment]
Solved with 82431cfdda0d52211ffcf06084e3a675a1330c64
