### ISSUE TITLE
Alarm are forgotten when phone reboots

### ISSUE THREAD

**Issue by RalfJung** [tuxmobil/CampFahrplan#125]
The title says it all...

Steps to reproduce:
* Set an alarm for an event.
* Reboot your phone.
* Open the app. There's no alarm.

I didn't exactly miss the opening event because of this, but I did miss the reminder for the opening event ;-)

**Comment by tuxmobil** [comment]
Thanks. Fixed in 1075d99b1c6c374724dc647502f9db10638b0529

**Comment by johnjohndoe** [comment]
The bug has been introduced in commit 1ac208e51d0acb46e157b9c68d7414f330fcbd9c.
