### ISSUE TITLE
NullPointerException when adding event to favorites after language change

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#151]
### Test environment
- Device: tablet (emulator)
- Commit: 20c2001a6631fc008b679e3c6579f6adb8cb6bef
- Flavor: ccc32c3
### Steps to reproduce
1. Select an event to show its details frame
2. Go into system settings and change language from English to German (or opposite)
3. Resume application
4. Select add to favorites icon in action bar
### Expected behavior
- The event details should still be shown after resume.
- Selecting the add to favorites icon will just work.
### Observed behavior
- Selecting the add to favorites icon causes a crash since `lecture` is `null`.

``` java
java.lang.NullPointerException: Attempt to write to field 'boolean 
    nerd.tuxmobil.fahrplan.congress.Lecture.highlight' on a null object reference
    at nerd.tuxmobil.fahrplan.congress.EventDetailFragment.onOptionsItemSelected(EventDetailFragment.java:312)
    at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2070)
    at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2159)
    at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:295)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:367)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)

```
### Quick fix
- The changes suggested in #150 will prevent the app from crashing. The remaining issue is bad user experience.

**Comment by johnjohndoe** [comment]
:white_check_mark: Resolved here: https://github.com/EventFahrplan/EventFahrplan/commit/3045e8eefc720b97f42b555c1569ccb15a151fa5

**Comment by junior291492659** [comment]
> ✅ Resolved here: [EventFahrplan@3045e8e](https://github.com/EventFahrplan/EventFahrplan/commit/3045e8eefc720b97f42b555c1569ccb15a151fa5)

hello, I can not understand why 'lecture' becomes null after the system language has been changed.It would appreciated to be replyed with explaination.Thanks! @johnjohndoe

**Comment by johnjohndoe** [comment]
@junior291492659 The solution from 2016 looks like a quick fix to me. I believe it would take a bit of time to dig into the problem to find the real reason. - Do you have a particular idea about the case?

**Comment by junior291492659** [comment]
> @junior291492659 The solution from 2016 looks like a quick fix to me. I believe it would take a bit of time to dig into the problem to find the real reason. - Do you have a particular idea about the case?

Hi, Thanks a lot for replying.really appreciated :). @johnjohndoe 
I tried to read the relevant source code but I can not figure it out since it can be chanlenging. Your quick fix is adding a judgement of nullness of 'lecture'.
According to the issue description, the observed behavior after the reproduce steps contains of clicking on the favorate button which causes the crash.
I wonder is the event details shown smoothly in the new language you changed to after resume ,then the action of clicking causes the crash.
I am sorry for not offering any idea about this issue but I am courious about the reason of 'lecture' becoming null after the system language has been changed so I searched for your help considering you are one of the contributors of this project. Thanks.

**Comment by johnjohndoe** [comment]
As a general advice, please do not take any solution/implementation for granted. Question all the things. As indicated before I believe that this particular fix has been a quick fix to mitigate the crashing effect not the source of the problem.
The easiest way to find out if the issue is still around would be to remove the null-check, compile and run the project and follow the steps to reproduce the crash. While doing that I like to point you to the [EventFahrplan repository](https://github.com/EventFahrplan/EventFahrplan) where the project is maintained since August 2017. - Please let me know if you need any help with that.
One question from my side: how comes that you are interested in this particular issue (since it has been closed for a while)?
