### ISSUE TITLE
notifications, unable to parse;

### ISSUE THREAD

**Issue by roberthesele** [tuxmobil/CampFahrplan#168]
hello fellow developer's!
android stock ROM, no #root, notifications doesn't work. click on the 🔄 icon, message:”unable to parse”.
cheers robert hesele (GDG-Vienna Austria Organiser)

**Comment by johnjohndoe** [comment]
@roberthesele Which app (there are multiple based on this source code) and version are you using? Further, the _Info_ screen shows the _Version hash_ at the bottom of the dialog. Do you use the preconfigured schedule URL or did you set a custom URL in the settings? If so, which?

**Comment by roberthesele** [comment]
hi all, for now android stock. 6.0.1, no #root, but now the notifications worked for me and the app is doing well. thanks for your support, robert

**Comment by johnjohndoe** [comment]
@roberthesele Good to hear the app works for you.
Although, I still I have no idea which app you are using:
- [32C3 Schedule](https://play.google.com/store/apps/details?id=nerd.tuxmobil.fahrplan.congress)
- [Camp 2015 Schedule](https://play.google.com/store/apps/details?id=nerd.tuxmobil.fahrplan.camp)
- another publication?

**Comment by roberthesele** [comment]
I'm sorry, Fahrplan 1.7👾 , appversion 0.5; and in the settings, (after no notifications work) I'm changing the link to: https://fahrplan.privacyweek.at/schedule/1.html; all works fine

**Comment by roberthesele** [comment]
downloaded from play store! sorry I got sick, my cognitively impaired to {=0}

**Comment by johnjohndoe** [comment]
Aaah! The [app for the Privacyweek](https://play.google.com/store/apps/details?id=net.wireloss.android.fahrplan.pw16) is developed by _Clemens Hopfer_ @oe1rfc. You should send him an email or leave a review comment in the Play store. You find his contact address at the bottom of the Play store page.

**Comment by roberthesele** [comment]
Hello, sorry for my mistakenly sent to you! thanks for your time! cheers

**Comment by johnjohndoe** [comment]
No problem. You are welcome.
