### ISSUE TITLE
No timezone offset

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#54]
Found this in the reviews in the PlayStore:

> This app doesnt have a timezone offset which makes the alarms a little useless for watching the streams here in the uk, other than that its great. // Dezember 27, 2011

Not sure if this is still valid.

**Comment by rponline** [comment]
I didn't check the alarm function, but the offset in the overview looks just fine.
An information about the timezone offset would be maybe a nice feature
