### ISSUE TITLE
Gradle: Could not find method android() for arguments

### ISSUE THREAD

**Issue by grote** [tuxmobil/CampFahrplan#62]
When updating the app for F-Droid, I get the following error when trying a gradle build for the 31c3 flavor:

```
Could not find method android() for arguments [build_3s0rukvj3lbgw5jd7doit49ke$_run_closure2@7fc75485] on root project 'nerd.tuxmobil.fahrplan.congress'.
```

Maybe, this is related: https://stackoverflow.com/questions/23115478/missing-main-module-in-android-studio

**Comment by MahbbRah** [comment]
# 

> [

- [ ] @1. 

](url)
