### ISSUE TITLE
Missing lecture background colors on a tablet

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#71]
I just noticed that the background colors on a tablet are gone if one uses the "alternative highlighting". The screenshots shows the rendering.

![Fahrplan on a tablet](https://cloud.githubusercontent.com/assets/144518/5568249/36d78384-8f56-11e4-833e-e6fe9a7d60b9.png)

It affects v.1.30.3 on a tablet. It does not affect the phone form factor.

**Comment by tuxmobil** [comment]
Please re-open if it appears again.
