### ISSUE TITLE
Schedule update mechanism doesn't support HTTP redirects

### ISSUE THREAD

**Issue by cketti** [tuxmobil/CampFahrplan#75]
The update mechanism doesn't follow HTTP redirects which makes using e.g. a URL shortener impossible.

**Comment by johnjohndoe** [comment]
@tuxmobil [Quoting @cketti](https://github.com/tuxmobil/CampFahrplan/pull/78#issuecomment-68326576) this issue is fixed since *OkHttp* is in place since [ef567](https://github.com/tuxmobil/CampFahrplan/commit/ef5677609435f4a036dcfa578004af25f8c8abbb).
