### ISSUE TITLE
Alarm is not removed automatically for past events

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#83]
I recently used the Fahrplan app for the **past** congress. I **added an alarm** for one of the events. Immediately, the alarm is fired and the notification appears in the menu. Normally the alarm clock symbol on the event pane should disappear now. The **alarm clock symbol stays** there. When I try to remove the alarm via the context menu action **the symbol does not get removed**.

**Comment by tuxmobil** [comment]
Fixed with 88bb76289efcc759842dba205ef0fcc41347e064

**Comment by johnjohndoe** [comment]
:+1:
