### ISSUE TITLE
CCCamp release

### ISSUE THREAD

**Issue by grote** [tuxmobil/CampFahrplan#85]
Hi,

a release with the camp schedule ahead of the camp would be nice, so we have time to get the release into F-Droid before the camp starts.

Thanks for the awesome app!

**Comment by tuxmobil** [comment]
I hope to release on tuesday.

**Comment by grote** [comment]
I saw you bumped the version name today, but not the version code.

**Comment by tuxmobil** [comment]
*cough* Thanks for noticing. I didn't, because I changed the package name.

**Comment by grote** [comment]
Alright, so a release has been made. Thanks for clarifying.
