### ISSUE TITLE
Loading the App brings you back to Day 1

### ISSUE THREAD

**Issue by blubbfish** [tuxmobil/CampFahrplan#95]
Every time even if the day 1 is over the app brings you back to day 1 when you open it

It would be bedder if the app loads the last seen day or only the day that is now present.

**Comment by johnjohndoe** [comment]
Thank you for reporting this issue. I could reproduce the faulty behavior in the Camp 2015 app and in the MRMCD15 app.

**Comment by tuxmobil** [comment]
Fixed with 5e19f30.
