### ISSUE TITLE
Empty view isn't inflated for favorites list after all favorites are deleted

### ISSUE THREAD

**Issue by johnjohndoe** [tuxmobil/CampFahrplan#97]
When no favorites are collected by the user the following screen with an "empty" text is shown:

![fahrplan-favorites-none](https://cloud.githubusercontent.com/assets/144518/10451230/34e4927a-719f-11e5-9a98-d92a464a5dcb.png)

Given the user collected favorites there is the option to delete all of them at once:

![fahrplan-alert-dialog-delete](https://cloud.githubusercontent.com/assets/144518/10451264/62fa092e-719f-11e5-9046-eeb464fdc82f.png)

When the deletion is confirmed the following screen shows up:

![fahrplan-favorites-empty](https://cloud.githubusercontent.com/assets/144518/10451279/76386cf6-719f-11e5-983b-9993b37329d2.png)

The screen missed the "empty" text.

**Comment by tuxmobil** [comment]
Any ideas why the mAdapter.notifyDataSetChanged(); doesn't do the trick?

**Comment by tuxmobil** [comment]
Fixed with 94c5b0e
